"""
Excel workbook export service.

Produces .xlsx workbooks for all report types using openpyxl.
Sheet builders are composable; package builders assemble multiple sheets.

Deterministic mode: pass deterministic=True (or a fixed generation_time) to
workbook_to_bytes() to get byte-stable output for the same data.
"""

from __future__ import annotations

import datetime
import io
import zipfile
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any, Sequence

import openpyxl
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from app.services.reporting_service import TrialBalanceRow
from app.services.fs_reporting_service import FsLineBalance
from app.services.draft_overlay_service import OverlayResult


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------

_HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
_HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
_SUBHEADER_FILL = PatternFill("solid", fgColor="D6E4F0")
_SUBHEADER_FONT = Font(bold=True, size=10)
_BOLD_FONT = Font(bold=True, size=10)
_NORMAL_FONT = Font(size=10)
_TOTAL_FONT = Font(bold=True, size=10, underline="singleAccounting")

_NUMBER_FMT = '#,##0.00'
_DATE_FMT = 'YYYY-MM-DD'

_FIXED_EPOCH = datetime.datetime(2000, 1, 1, 0, 0, 0)


# ---------------------------------------------------------------------------
# Metadata carrier
# ---------------------------------------------------------------------------

@dataclass
class WorkbookMeta:
    report_type: str
    entity_name: str = ""
    organization_name: str = ""
    as_of_date: datetime.date | None = None
    scenario_labels: list[str] = field(default_factory=list)
    period_name: str = ""
    generated_by: str = ""
    generation_time: datetime.datetime | None = None
    extra: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _write_header_row(ws, values: list[str], row: int = 1) -> None:
    for col, val in enumerate(values, start=1):
        cell = ws.cell(row=row, column=col, value=val)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = Alignment(horizontal="center")


def _write_subheader_row(ws, values: list[str], row: int) -> None:
    for col, val in enumerate(values, start=1):
        cell = ws.cell(row=row, column=col, value=val)
        cell.font = _SUBHEADER_FONT
        cell.fill = _SUBHEADER_FILL


def _write_label_value(ws, row: int, label: str, value: Any) -> None:
    ws.cell(row=row, column=1, value=label).font = _BOLD_FONT
    ws.cell(row=row, column=2, value=value).font = _NORMAL_FONT


def _auto_width(ws, min_width: int = 10, max_width: int = 50) -> None:
    for col in ws.columns:
        best = min_width
        for cell in col:
            if cell.value is not None:
                best = min(max(best, len(str(cell.value)) + 2), max_width)
        ws.column_dimensions[get_column_letter(col[0].column)].width = best


def _set_number_col(ws, col: int, start_row: int, end_row: int) -> None:
    for row in range(start_row, end_row + 1):
        ws.cell(row=row, column=col).number_format = _NUMBER_FMT


# ---------------------------------------------------------------------------
# Sheet builders
# ---------------------------------------------------------------------------

def _add_cover_sheet(wb: Workbook, meta: WorkbookMeta) -> None:
    ws = wb.active
    ws.title = "Cover"
    ws.sheet_properties.tabColor = "1F4E79"

    title_cell = ws.cell(row=1, column=1, value=meta.report_type.replace("_", " ").title())
    title_cell.font = Font(bold=True, size=16, color="1F4E79")
    ws.merge_cells("A1:D1")

    _write_label_value(ws, 3, "Entity", meta.entity_name)
    _write_label_value(ws, 4, "Organization", meta.organization_name)
    if meta.as_of_date:
        _write_label_value(ws, 5, "As of Date", str(meta.as_of_date))
    if meta.period_name:
        _write_label_value(ws, 6, "Period", meta.period_name)
    if meta.scenario_labels:
        _write_label_value(ws, 7, "Scenarios", ", ".join(meta.scenario_labels))
    generated_at = meta.generation_time or datetime.datetime.now(datetime.UTC)
    _write_label_value(ws, 8, "Generated At", str(generated_at))
    if meta.generated_by:
        _write_label_value(ws, 9, "Generated By", meta.generated_by)

    ws.column_dimensions["A"].width = 18
    ws.column_dimensions["B"].width = 35


def _add_metadata_sheet(wb: Workbook, meta: WorkbookMeta) -> None:
    ws = wb.create_sheet("Metadata")
    _write_header_row(ws, ["Key", "Value"])
    pairs = [
        ("report_type", meta.report_type),
        ("entity_name", meta.entity_name),
        ("organization_name", meta.organization_name),
        ("as_of_date", str(meta.as_of_date) if meta.as_of_date else ""),
        ("period_name", meta.period_name),
        ("scenarios", ",".join(meta.scenario_labels)),
        ("generated_by", meta.generated_by),
        ("generation_time", str(meta.generation_time or "")),
    ]
    for extra_k, extra_v in meta.extra.items():
        pairs.append((extra_k, str(extra_v)))
    for row, (k, v) in enumerate(pairs, start=2):
        ws.cell(row=row, column=1, value=k)
        ws.cell(row=row, column=2, value=v)
    _auto_width(ws)


def _add_tb_sheet(
    wb: Workbook,
    rows: Sequence[TrialBalanceRow],
    sheet_title: str = "Trial Balance",
) -> None:
    ws = wb.create_sheet(sheet_title)
    headers = [
        "Account #", "Account Name", "Type", "Normal Balance",
        "Total Debit", "Total Credit", "Net Debit", "Signed Balance",
    ]
    _write_header_row(ws, headers)

    for r, row in enumerate(rows, start=2):
        ws.cell(row=r, column=1, value=row.account_number)
        ws.cell(row=r, column=2, value=row.account_name)
        ws.cell(row=r, column=3, value=row.account_type)
        ws.cell(row=r, column=4, value=row.normal_balance)
        ws.cell(row=r, column=5, value=float(row.total_debit))
        ws.cell(row=r, column=6, value=float(row.total_credit))
        ws.cell(row=r, column=7, value=float(row.net_debit))
        ws.cell(row=r, column=8, value=float(row.signed_balance))

    if rows:
        end = len(rows) + 1
        for col in (5, 6, 7, 8):
            _set_number_col(ws, col, 2, end)
        # totals row
        total_row = end + 1
        ws.cell(row=total_row, column=2, value="TOTAL").font = _TOTAL_FONT
        for col_idx, attr in ((5, "total_debit"), (6, "total_credit"),
                              (7, "net_debit"), (8, "signed_balance")):
            total = sum(getattr(r, attr) for r in rows)
            cell = ws.cell(row=total_row, column=col_idx, value=float(total))
            cell.font = _TOTAL_FONT
            cell.number_format = _NUMBER_FMT

    _auto_width(ws)


def _add_fs_sheet(
    wb: Workbook,
    lines: Sequence[FsLineBalance],
    statement_filter: str | None = None,
    sheet_title: str | None = None,
) -> None:
    filtered = [l for l in lines if statement_filter is None or l.statement == statement_filter]
    title = sheet_title or (statement_filter or "Financial Statements")
    ws = wb.create_sheet(title)
    headers = ["Code", "Name", "Section", "Subtotal?", "Display Balance"]
    _write_header_row(ws, headers)

    for r, line in enumerate(sorted(filtered, key=lambda x: x.sort_order), start=2):
        ws.cell(row=r, column=1, value=line.code)
        name_cell = ws.cell(row=r, column=2, value=line.name)
        ws.cell(row=r, column=3, value=line.section or "")
        ws.cell(row=r, column=4, value="Yes" if line.is_subtotal else "")
        val_cell = ws.cell(row=r, column=5, value=float(line.display_balance))
        val_cell.number_format = _NUMBER_FMT
        if line.is_subtotal:
            name_cell.font = _BOLD_FONT
            val_cell.font = _BOLD_FONT

    _auto_width(ws)


def _add_validation_sheet(wb: Workbook, validation_items: list[dict]) -> None:
    ws = wb.create_sheet("Validation")
    headers = ["Severity", "Code", "Message", "Source Type", "Source ID", "Suggested Resolution"]
    _write_header_row(ws, headers)

    severity_colors = {
        "ERROR": "FFCCCC",
        "WARNING": "FFF2CC",
        "INFO": "E2EFDA",
    }
    for r, item in enumerate(validation_items, start=2):
        sev = str(item.get("severity", "")).upper()
        ws.cell(row=r, column=1, value=sev)
        ws.cell(row=r, column=2, value=item.get("code", ""))
        ws.cell(row=r, column=3, value=item.get("message", ""))
        ws.cell(row=r, column=4, value=item.get("source_type", ""))
        ws.cell(row=r, column=5, value=str(item.get("source_id", "") or ""))
        ws.cell(row=r, column=6, value=item.get("suggested_resolution", "") or "")
        fill_color = severity_colors.get(sev)
        if fill_color:
            row_fill = PatternFill("solid", fgColor=fill_color)
            for col in range(1, 7):
                ws.cell(row=r, column=col).fill = row_fill

    _auto_width(ws)


def _add_workflow_sheet(wb: Workbook, tasks: list[dict], signoffs: list[dict]) -> None:
    ws = wb.create_sheet("Workflow")

    ws.cell(row=1, column=1, value="Tasks").font = _BOLD_FONT
    task_headers = ["ID", "Title", "Type", "Status", "Priority", "Assigned To", "Due Date"]
    _write_subheader_row(ws, task_headers, row=2)
    task_row = 3
    for t in tasks:
        ws.cell(row=task_row, column=1, value=t.get("id"))
        ws.cell(row=task_row, column=2, value=t.get("title", ""))
        ws.cell(row=task_row, column=3, value=t.get("task_type", ""))
        ws.cell(row=task_row, column=4, value=t.get("status", ""))
        ws.cell(row=task_row, column=5, value=t.get("priority", ""))
        ws.cell(row=task_row, column=6, value=str(t.get("assigned_to_user_id") or ""))
        ws.cell(row=task_row, column=7, value=str(t.get("due_date") or ""))
        task_row += 1

    signoff_start = task_row + 2
    ws.cell(row=signoff_start, column=1, value="Signoffs").font = _BOLD_FONT
    sig_headers = ["ID", "Object Type", "Object ID", "Reviewer", "Status", "Signed At", "Notes"]
    _write_subheader_row(ws, sig_headers, row=signoff_start + 1)
    sig_row = signoff_start + 2
    for s in signoffs:
        ws.cell(row=sig_row, column=1, value=s.get("id"))
        ws.cell(row=sig_row, column=2, value=s.get("object_type", ""))
        ws.cell(row=sig_row, column=3, value=s.get("object_id"))
        ws.cell(row=sig_row, column=4, value=str(s.get("reviewer_user_id") or ""))
        ws.cell(row=sig_row, column=5, value=s.get("signoff_status", ""))
        ws.cell(row=sig_row, column=6, value=str(s.get("signed_at") or ""))
        ws.cell(row=sig_row, column=7, value=s.get("notes") or "")
        sig_row += 1

    _auto_width(ws)


def _add_issues_sheet(wb: Workbook, issues: list[dict]) -> None:
    ws = wb.create_sheet("Issues")
    headers = ["ID", "Code", "Severity", "Title", "Status", "Object Type", "Object ID",
               "Opened At", "Resolved At", "Resolution Notes"]
    _write_header_row(ws, headers)

    for r, issue in enumerate(issues, start=2):
        ws.cell(row=r, column=1, value=issue.get("id"))
        ws.cell(row=r, column=2, value=issue.get("issue_code", ""))
        ws.cell(row=r, column=3, value=issue.get("severity", ""))
        ws.cell(row=r, column=4, value=issue.get("title", ""))
        ws.cell(row=r, column=5, value=issue.get("status", ""))
        ws.cell(row=r, column=6, value=issue.get("related_object_type") or "")
        ws.cell(row=r, column=7, value=str(issue.get("related_object_id") or ""))
        ws.cell(row=r, column=8, value=str(issue.get("opened_at") or ""))
        ws.cell(row=r, column=9, value=str(issue.get("resolved_at") or ""))
        ws.cell(row=r, column=10, value=issue.get("resolution_notes") or "")

    _auto_width(ws)


# ---------------------------------------------------------------------------
# Public workbook builders
# ---------------------------------------------------------------------------

def build_trial_balance_workbook(
    meta: WorkbookMeta,
    tb_rows: Sequence[TrialBalanceRow],
    validation_items: list[dict] | None = None,
    workflow_tasks: list[dict] | None = None,
    workflow_signoffs: list[dict] | None = None,
    issues: list[dict] | None = None,
) -> Workbook:
    wb = Workbook()
    _add_cover_sheet(wb, meta)
    _add_metadata_sheet(wb, meta)
    _add_tb_sheet(wb, tb_rows, "Trial Balance")
    if validation_items:
        _add_validation_sheet(wb, validation_items)
    if workflow_tasks is not None or workflow_signoffs is not None:
        _add_workflow_sheet(wb, workflow_tasks or [], workflow_signoffs or [])
    if issues:
        _add_issues_sheet(wb, issues)
    return wb


def build_fs_workbook(
    meta: WorkbookMeta,
    tb_rows: Sequence[TrialBalanceRow],
    fs_lines: Sequence[FsLineBalance],
    validation_items: list[dict] | None = None,
    workflow_tasks: list[dict] | None = None,
    workflow_signoffs: list[dict] | None = None,
    issues: list[dict] | None = None,
) -> Workbook:
    wb = Workbook()
    _add_cover_sheet(wb, meta)
    _add_metadata_sheet(wb, meta)
    _add_tb_sheet(wb, tb_rows, "Trial Balance")

    bs_lines = [l for l in fs_lines if l.statement == "BS"]
    is_lines = [l for l in fs_lines if l.statement == "IS"]
    cf_lines = [l for l in fs_lines if l.statement == "CF"]
    if bs_lines:
        _add_fs_sheet(wb, bs_lines, sheet_title="Balance Sheet")
    if is_lines:
        _add_fs_sheet(wb, is_lines, sheet_title="Income Statement")
    if cf_lines:
        _add_fs_sheet(wb, cf_lines, sheet_title="Cash Flow")

    if validation_items:
        _add_validation_sheet(wb, validation_items)
    if workflow_tasks is not None or workflow_signoffs is not None:
        _add_workflow_sheet(wb, workflow_tasks or [], workflow_signoffs or [])
    if issues:
        _add_issues_sheet(wb, issues)
    return wb


def build_close_package_workbook(
    meta: WorkbookMeta,
    tb_rows: Sequence[TrialBalanceRow],
    fs_lines: Sequence[FsLineBalance],
    validation_items: list[dict] | None = None,
    workflow_tasks: list[dict] | None = None,
    workflow_signoffs: list[dict] | None = None,
    issues: list[dict] | None = None,
) -> Workbook:
    return build_fs_workbook(
        meta, tb_rows, fs_lines,
        validation_items=validation_items,
        workflow_tasks=workflow_tasks,
        workflow_signoffs=workflow_signoffs,
        issues=issues,
    )


def build_preview_workbook(result: OverlayResult) -> Workbook:
    """
    Build an Excel workbook for a draft-impact preview.

    EXPORT RULES:
    - Cover sheet MUST display the DRAFT PREVIEW warning prominently.
    - Sheet names include "DRAFT" prefix.
    - All numeric columns display official, adjustment, and preview amounts side-by-side.
    - This workbook MUST NEVER be used as an official financial statement.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Cover"

    # --- DRAFT PREVIEW warning header (red, prominent) ---
    warn_cell = ws.cell(row=1, column=1, value="⚠  DRAFT PREVIEW — NOT POSTED — NOT OFFICIAL  ⚠")
    warn_cell.font = Font(bold=True, size=14, color="CC0000")
    warn_cell.fill = PatternFill("solid", fgColor="FFF2CC")
    ws.merge_cells("A1:F1")

    title_cell = ws.cell(row=2, column=1, value=f"Preview Type: {result.preview_type.replace('_', ' ').title()}")
    title_cell.font = Font(bold=True, size=13, color="1F4E79")
    ws.merge_cells("A2:F2")

    _write_label_value(ws, 4,  "Preview Label",    result.label)
    _write_label_value(ws, 5,  "As of Date",        str(result.as_of_date))
    _write_label_value(ws, 6,  "Entity ID",         result.entity_id)
    _write_label_value(ws, 7,  "Scenario ID",       result.scenario_id)
    _write_label_value(ws, 8,  "Generated At",      str(result.generated_at))
    _write_label_value(ws, 9,  "Draft Entries Included", result.included_je_count)
    _write_label_value(ws, 10, "Overlay Groups",    ", ".join(result.overlay_groups) if result.overlay_groups else "All")
    _write_label_value(ws, 11, "RE Rollforward",    "Yes" if result.re_rollforward_applied else "No")
    _write_label_value(ws, 12, "Consolidated",      "Yes" if result.member_entity_ids else "No")

    ws.cell(row=14, column=1,
            value="This file is a DRAFT PREVIEW. Do not distribute as official financial data."
            ).font = Font(italic=True, color="CC0000", size=9)

    ws.column_dimensions["A"].width = 26
    ws.column_dimensions["B"].width = 40

    # --- Preview data sheet ---
    ds = wb.create_sheet("DRAFT PREVIEW Data")
    headers = [
        "Account ID", "Account Number", "Account Name", "Account Type", "Normal Balance",
        "Official Balance (Posted)", "Draft Adjustment", "Preview Balance",
        "Source JE IDs", "Overlay Groups",
    ]
    _write_header_row(ds, headers)

    for r, item in enumerate(result.line_items, start=2):
        ds.cell(row=r, column=1, value=item.account_id)
        ds.cell(row=r, column=2, value=item.account_number)
        ds.cell(row=r, column=3, value=item.account_name)
        ds.cell(row=r, column=4, value=item.account_type)
        ds.cell(row=r, column=5, value=item.normal_balance)
        ds.cell(row=r, column=6, value=float(item.official_signed_balance)).number_format = _NUMBER_FMT
        ds.cell(row=r, column=7, value=float(item.draft_signed_adjustment)).number_format = _NUMBER_FMT
        ds.cell(row=r, column=8, value=float(item.preview_signed_balance)).number_format = _NUMBER_FMT
        ds.cell(row=r, column=9, value=",".join(str(i) for i in item.source_je_ids))
        ds.cell(row=r, column=10, value=",".join(item.overlay_groups_used))
        if item.is_synthetic_re:
            for col in range(1, 11):
                ds.cell(row=r, column=col).font = Font(italic=True, color="7030A0")

    _auto_width(ds)

    # --- Overlay summary sheet ---
    ss = wb.create_sheet("Overlay Summary")
    ss.cell(row=1, column=1, value="DRAFT PREVIEW — Overlay Summary").font = Font(bold=True, size=12, color="CC0000")
    ss.cell(row=2, column=1, value=f"Included draft JEs: {result.included_je_count}")
    ss.cell(row=3, column=1, value=f"Overlay groups: {', '.join(result.overlay_groups) if result.overlay_groups else 'All'}")
    ss.cell(row=4, column=1, value=f"RE rollforward applied: {'Yes' if result.re_rollforward_applied else 'No'}")
    if result.re_rollforward_applied:
        ss.cell(row=5, column=1, value=f"RE draft adjustment: {float(result.re_draft_adjustment):.2f}")

    # By-group breakdown
    ss.cell(row=7, column=1, value="Adjustments by Overlay Group").font = _SUBHEADER_FONT
    group_totals: dict[str, float] = {}
    for item in result.line_items:
        for grp in item.overlay_groups_used:
            group_totals[grp] = group_totals.get(grp, 0.0) + float(item.draft_signed_adjustment)
    for r, (grp, total) in enumerate(sorted(group_totals.items()), start=8):
        ss.cell(row=r, column=1, value=grp)
        ss.cell(row=r, column=2, value=total).number_format = _NUMBER_FMT

    _auto_width(ss)
    return wb


def build_reconciliation_workbook(recon, lines, support_refs) -> Workbook:
    """
    Build a reconciliation workbook with:
    - Cover sheet with RECONCILIATION label and variance summary
    - Detail sheet with reconciliation lines
    - Support sheet listing all support references
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Reconciliation"

    # Header
    warning_cell = ws.cell(row=1, column=1, value="ACCOUNT RECONCILIATION — PREPARED BY MANAGEMENT")
    warning_cell.font = Font(bold=True, size=12)
    warning_cell.fill = PatternFill("solid", fgColor="D6E4F0")
    ws.merge_cells("A1:D1")

    _write_label_value(ws, 3, "Reconciliation ID", recon.id)
    _write_label_value(ws, 4, "Account ID", recon.account_id)
    _write_label_value(ws, 5, "Status", recon.status)
    _write_label_value(ws, 6, "Type", recon.reconciliation_type)
    _write_label_value(ws, 7, "Official Balance", float(recon.official_balance) if recon.official_balance is not None else "—")
    _write_label_value(ws, 8, "Supporting Balance", float(recon.supporting_balance) if recon.supporting_balance is not None else "—")
    variance_val = float(recon.variance_amount) if recon.variance_amount is not None else "—"
    _write_label_value(ws, 9, "Variance", variance_val)
    _write_label_value(ws, 10, "Tie-Out Status", recon.tie_out_status)
    if recon.variance_explanation:
        _write_label_value(ws, 11, "Variance Explanation", recon.variance_explanation)

    ws.column_dimensions["A"].width = 26
    ws.column_dimensions["B"].width = 40

    # Lines sheet
    ls = wb.create_sheet("Reconciliation Lines")
    _write_header_row(ls, ["Line #", "Description", "Source Type", "Source Ref", "Debit", "Credit", "Balance", "Reconciling Item", "Notes"])
    for r, line in enumerate(lines, start=2):
        ls.cell(row=r, column=1, value=line.line_number)
        ls.cell(row=r, column=2, value=line.description)
        ls.cell(row=r, column=3, value=line.source_type)
        ls.cell(row=r, column=4, value=line.source_reference)
        ls.cell(row=r, column=5, value=float(line.debit)).number_format = _NUMBER_FMT
        ls.cell(row=r, column=6, value=float(line.credit)).number_format = _NUMBER_FMT
        ls.cell(row=r, column=7, value=float(line.balance)).number_format = _NUMBER_FMT
        ls.cell(row=r, column=8, value="Yes" if line.is_reconciling_item else "No")
        ls.cell(row=r, column=9, value=line.reconciling_notes)
    _auto_width(ls)

    # Support references sheet
    ss = wb.create_sheet("Support References")
    _write_header_row(ss, ["ID", "Type", "Document ID", "JE ID", "External Ref", "Description"])
    for r, ref in enumerate(support_refs, start=2):
        ss.cell(row=r, column=1, value=ref.id)
        ss.cell(row=r, column=2, value=ref.reference_type)
        ss.cell(row=r, column=3, value=ref.document_id)
        ss.cell(row=r, column=4, value=ref.journal_entry_id)
        ss.cell(row=r, column=5, value=ref.external_ref)
        ss.cell(row=r, column=6, value=ref.description)
    _auto_width(ss)

    _auto_width(ws)
    return wb


def build_lender_package_workbook(
    meta: WorkbookMeta,
    tb_rows: Sequence[TrialBalanceRow],
    fs_lines: Sequence[FsLineBalance],
    validation_items: list[dict] | None = None,
    issues: list[dict] | None = None,
) -> Workbook:
    # Lender package: no internal workflow details, clean FS + TB
    wb = Workbook()
    _add_cover_sheet(wb, meta)
    _add_metadata_sheet(wb, meta)
    _add_tb_sheet(wb, tb_rows, "Trial Balance")
    bs_lines = [l for l in fs_lines if l.statement == "BS"]
    is_lines = [l for l in fs_lines if l.statement == "IS"]
    if bs_lines:
        _add_fs_sheet(wb, bs_lines, sheet_title="Balance Sheet")
    if is_lines:
        _add_fs_sheet(wb, is_lines, sheet_title="Income Statement")
    if validation_items:
        _add_validation_sheet(wb, validation_items)
    if issues:
        _add_issues_sheet(wb, issues)
    return wb


# ---------------------------------------------------------------------------
# Close Package / Board Package / Lender Package — M20
# ---------------------------------------------------------------------------

_WATERMARK_FILLS = {
    "DRAFT":    PatternFill("solid", fgColor="FFF2CC"),
    "PREVIEW":  PatternFill("solid", fgColor="FCE4D6"),
    "INTERNAL": PatternFill("solid", fgColor="E2EFDA"),
    "OFFICIAL": PatternFill("solid", fgColor="DEEAF1"),
}
_WATERMARK_FONT_COLORS = {
    "DRAFT":    "CC7A00",
    "PREVIEW":  "CC0000",
    "INTERNAL": "375623",
    "OFFICIAL": "1F4E79",
}


def _add_watermark_banner(ws, watermark: str, row: int = 1) -> None:
    fill = _WATERMARK_FILLS.get(watermark, _WATERMARK_FILLS["DRAFT"])
    color = _WATERMARK_FONT_COLORS.get(watermark, "CC0000")
    cell = ws.cell(
        row=row, column=1,
        value=f"⚠  {watermark} — FOR INTERNAL USE ONLY. NOT FOR DISTRIBUTION.  ⚠"
    )
    cell.font = Font(bold=True, size=12, color=color)
    cell.fill = fill
    cell.alignment = Alignment(horizontal="center")


def build_watermarked_close_package(
    entity_id: int,
    as_of_date,
    scenario_ids: list,
    tb_rows,
    fs_lines,
    cf_result=None,
    label: str = "Close Package",
    watermark: str = "DRAFT",
) -> Workbook:
    """
    Build a complete close package workbook with watermarking.

    Sheets: Cover | Trial Balance | Balance Sheet | Income Statement | Cash Flow
    """
    wb = Workbook()

    # --- Cover sheet ---
    ws = wb.active
    ws.title = "Cover"
    _add_watermark_banner(ws, watermark, row=1)
    ws.merge_cells("A1:F1")
    ws.cell(row=3, column=1, value=label).font = Font(bold=True, size=14)
    ws.cell(row=4, column=1, value=f"Entity ID: {entity_id}")
    ws.cell(row=5, column=1, value=f"As of Date: {as_of_date}")
    ws.cell(row=6, column=1, value=f"Scenario IDs: {', '.join(str(s) for s in scenario_ids)}")
    ws.cell(row=7, column=1, value=f"Status: {watermark}")
    ws.column_dimensions["A"].width = 40

    # --- Trial Balance sheet ---
    _add_tb_sheet(wb, tb_rows, "Trial Balance")
    tb_ws = wb["Trial Balance"]
    _add_watermark_banner(tb_ws, watermark, row=1)

    # --- Balance Sheet ---
    bs_lines = [l for l in fs_lines if l.statement == "BS"]
    if bs_lines:
        _add_fs_sheet(wb, bs_lines, sheet_title="Balance Sheet")
        _add_watermark_banner(wb["Balance Sheet"], watermark, row=1)

    # --- Income Statement ---
    is_lines = [l for l in fs_lines if l.statement == "IS"]
    if is_lines:
        _add_fs_sheet(wb, is_lines, sheet_title="Income Statement")
        _add_watermark_banner(wb["Income Statement"], watermark, row=1)

    # --- Cash Flow sheet ---
    if cf_result is not None:
        cfs = wb.create_sheet("Cash Flow Statement")
        _add_watermark_banner(cfs, watermark, row=1)
        cfs.merge_cells("A1:C1")
        cfs.cell(row=2, column=1, value="Statement of Cash Flows (Indirect Method)").font = Font(bold=True, size=12)
        cfs.cell(row=3, column=1, value=f"Period: {cf_result.period_start} to {cf_result.period_end}")

        row = 5
        for section in (cf_result.operating, cf_result.investing, cf_result.financing):
            cfs.cell(row=row, column=1, value=section.label).font = _SUBHEADER_FONT
            cfs.cell(row=row, column=1).fill = _SUBHEADER_FILL
            row += 1
            for line in section.lines:
                indent = "    " if not line.is_subtotal else ""
                cfs.cell(row=row, column=1, value=f"{indent}{line.label}")
                cell = cfs.cell(row=row, column=2, value=float(line.amount))
                cell.number_format = _NUMBER_FMT
                if line.is_subtotal:
                    cfs.cell(row=row, column=1).font = _BOLD_FONT
                    cell.font = _BOLD_FONT
                row += 1
            row += 1

        cfs.cell(row=row, column=1, value="Net Change in Cash").font = _BOLD_FONT
        cfs.cell(row=row, column=2, value=float(cf_result.net_change)).number_format = _NUMBER_FMT
        cfs.cell(row=row, column=2).font = _BOLD_FONT
        row += 1
        cfs.cell(row=row, column=1, value="Beginning Cash")
        cfs.cell(row=row, column=2, value=float(cf_result.beginning_cash)).number_format = _NUMBER_FMT
        row += 1
        cfs.cell(row=row, column=1, value="Ending Cash")
        cfs.cell(row=row, column=2, value=float(cf_result.ending_cash)).number_format = _NUMBER_FMT

        if cf_result.warnings:
            row += 2
            cfs.cell(row=row, column=1, value="Warnings:").font = Font(bold=True, color="CC0000")
            for w in cf_result.warnings:
                row += 1
                cfs.cell(row=row, column=1, value=w).font = Font(color="CC0000", size=9)

        cfs.column_dimensions["A"].width = 40
        cfs.column_dimensions["B"].width = 16

    return wb


# ---------------------------------------------------------------------------
# Serialisation
# ---------------------------------------------------------------------------

def _make_deterministic(data: bytes, fixed_time: datetime.datetime) -> bytes:
    """Re-zip an xlsx blob with fixed timestamps to make output byte-stable."""
    fixed_dt = (
        fixed_time.year, fixed_time.month, fixed_time.day,
        fixed_time.hour, fixed_time.minute, fixed_time.second,
    )
    in_buf = io.BytesIO(data)
    out_buf = io.BytesIO()
    with zipfile.ZipFile(in_buf, "r") as zin, \
         zipfile.ZipFile(out_buf, "w", compression=zipfile.ZIP_DEFLATED) as zout:
        for item in sorted(zin.infolist(), key=lambda i: i.filename):
            item.date_time = fixed_dt
            item.compress_type = zipfile.ZIP_DEFLATED
            zout.writestr(item, zin.read(item.filename))
    return out_buf.getvalue()


def workbook_to_bytes(
    wb: Workbook,
    generation_time: datetime.datetime | None = None,
    *,
    deterministic: bool = False,
) -> bytes:
    """
    Serialize a workbook to xlsx bytes.

    Parameters
    ----------
    generation_time
        If provided, sets wb.properties.created and .modified to this value.
    deterministic
        If True, re-zips with fixed timestamps so identical data produces
        identical checksums.  Automatically pins generation_time to
        _FIXED_EPOCH when not supplied.
    """
    if deterministic and generation_time is None:
        generation_time = _FIXED_EPOCH

    if generation_time is not None:
        wb.properties.created = generation_time
        wb.properties.modified = generation_time

    buf = io.BytesIO()
    wb.save(buf)
    data = buf.getvalue()

    if deterministic:
        data = _make_deterministic(data, generation_time)  # type: ignore[arg-type]

    return data
