"""
Report-run orchestration service.

Responsibilities
----------------
- Create and persist ReportRun records
- Dispatch execution to the export service
- Store generated bytes via StorageBackend
- Create a Document record and link it to the run on completion
- Populate validation_summary_json and workflow_summary_json
"""

from __future__ import annotations

import datetime
import json
import uuid
from typing import TYPE_CHECKING

from sqlalchemy.orm import Session

from app.models.report_run import (
    OUTPUT_FORMATS,
    REPORT_TYPE_DOC_TYPE,
    REPORT_TYPES,
    ReportRun,
)

if TYPE_CHECKING:
    from app.models.user import User
    from app.services.storage_service import StorageBackend


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class ReportRunNotFoundError(LookupError):
    pass


class ReportRunStateError(ValueError):
    pass


class ReportValidationError(ValueError):
    pass


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_scenario_ids(run: ReportRun) -> list[int]:
    if not run.scenario_ids_json:
        return []
    return json.loads(run.scenario_ids_json)


def _build_validation_summary(result) -> dict:
    """Convert a ValidationResult to a JSON-serialisable dict."""
    if result is None:
        return {"success": True, "errors": [], "warnings": [], "info": []}
    return {
        "success": result.success,
        "errors": [i.to_dict() for i in result.errors],
        "warnings": [i.to_dict() for i in result.warnings],
        "info": [i.to_dict() for i in result.infos],
    }


def _collect_workflow_summary(
    db: Session,
    run: ReportRun,
) -> dict:
    """Pull open tasks and signoffs related to the entity/period for the run."""
    from app.services.workflow_service import list_issues, list_signoffs, list_tasks

    tasks_data: list[dict] = []
    signoffs_data: list[dict] = []
    issues_data: list[dict] = []

    if run.organization_id:
        raw_tasks = list_tasks(db, run.organization_id)
        tasks_data = [
            {
                "id": t.id,
                "title": t.title,
                "task_type": t.task_type,
                "status": t.status,
                "priority": t.priority,
                "assigned_to_user_id": t.assigned_to_user_id,
                "due_date": str(t.due_date) if t.due_date else None,
            }
            for t in raw_tasks
        ]
        raw_issues = list_issues(db, run.organization_id)
        issues_data = [
            {
                "id": i.id,
                "issue_code": i.issue_code,
                "severity": i.severity,
                "title": i.title,
                "status": i.status,
                "related_object_type": i.related_object_type,
                "related_object_id": i.related_object_id,
                "opened_at": str(i.opened_at) if i.opened_at else None,
                "resolved_at": str(i.resolved_at) if i.resolved_at else None,
                "resolution_notes": i.resolution_notes,
            }
            for i in raw_issues
        ]

    if run.accounting_period_id:
        raw_signoffs = list_signoffs(db, "accounting_period", run.accounting_period_id)
        signoffs_data = [
            {
                "id": s.id,
                "object_type": s.object_type,
                "object_id": s.object_id,
                "reviewer_user_id": s.reviewer_user_id,
                "signoff_status": s.signoff_status,
                "signed_at": str(s.signed_at) if s.signed_at else None,
                "notes": s.notes,
            }
            for s in raw_signoffs
        ]

    return {
        "tasks": tasks_data,
        "signoffs": signoffs_data,
        "issues": issues_data,
    }


def _dispatch_report(db: Session, run: ReportRun) -> bytes:
    """Build the workbook bytes for a report run."""
    from app.models.entity import Entity
    from app.models.organization import Organization
    from app.services.export_service import (
        WorkbookMeta,
        build_close_package_workbook,
        build_fs_workbook,
        build_lender_package_workbook,
        build_trial_balance_workbook,
        workbook_to_bytes,
    )
    from app.services.fs_reporting_service import get_fs_statement
    from app.services.reporting_service import get_trial_balance

    params: dict = json.loads(run.parameters_json) if run.parameters_json else {}
    scenario_ids = _get_scenario_ids(run)
    as_of_date_str = params.get("as_of_date")
    as_of_date = (
        datetime.date.fromisoformat(as_of_date_str)
        if as_of_date_str
        else datetime.date.today()
    )

    entity = db.get(Entity, run.entity_id) if run.entity_id else None
    org = db.get(Organization, run.organization_id) if run.organization_id else None
    entity_name = entity.name if entity else ""
    org_name = org.name if org else ""

    meta = WorkbookMeta(
        report_type=run.report_type,
        entity_name=entity_name,
        organization_name=org_name,
        as_of_date=as_of_date,
        generation_time=datetime.datetime.now(datetime.UTC),
    )

    wf_summary = json.loads(run.workflow_summary_json) if run.workflow_summary_json else {}
    tasks = wf_summary.get("tasks", [])
    signoffs = wf_summary.get("signoffs", [])
    issues = wf_summary.get("issues", [])

    val_summary = json.loads(run.validation_summary_json) if run.validation_summary_json else {}
    validation_items: list[dict] = []
    for sev_key in ("errors", "warnings", "info"):
        validation_items.extend(val_summary.get(sev_key, []))

    rtype = run.report_type

    if rtype in ("trial_balance", "comparative_trial_balance",
                 "consolidated_trial_balance"):
        if run.entity_id and scenario_ids:
            tb_rows = get_trial_balance(db, run.entity_id, as_of_date, scenario_ids)
        else:
            tb_rows = []
        wb = build_trial_balance_workbook(
            meta, tb_rows,
            validation_items=validation_items or None,
            workflow_tasks=tasks,
            workflow_signoffs=signoffs,
            issues=issues or None,
        )

    elif rtype in ("balance_sheet", "income_statement",
                   "consolidated_balance_sheet", "consolidated_income_statement"):
        if run.entity_id and scenario_ids:
            tb_rows = get_trial_balance(db, run.entity_id, as_of_date, scenario_ids)
            fs_lines = get_fs_statement(db, run.entity_id, as_of_date, scenario_ids)
        else:
            tb_rows = []
            fs_lines = []
        wb = build_fs_workbook(
            meta, tb_rows, fs_lines,
            validation_items=validation_items or None,
            workflow_tasks=tasks,
            workflow_signoffs=signoffs,
            issues=issues or None,
        )

    elif rtype in ("close_package", "audit_support_package", "qoe_package"):
        if run.entity_id and scenario_ids:
            tb_rows = get_trial_balance(db, run.entity_id, as_of_date, scenario_ids)
            fs_lines = get_fs_statement(db, run.entity_id, as_of_date, scenario_ids)
        else:
            tb_rows = []
            fs_lines = []
        wb = build_close_package_workbook(
            meta, tb_rows, fs_lines,
            validation_items=validation_items or None,
            workflow_tasks=tasks,
            workflow_signoffs=signoffs,
            issues=issues or None,
        )

    elif rtype == "lender_package":
        if run.entity_id and scenario_ids:
            tb_rows = get_trial_balance(db, run.entity_id, as_of_date, scenario_ids)
            fs_lines = get_fs_statement(db, run.entity_id, as_of_date, scenario_ids)
        else:
            tb_rows = []
            fs_lines = []
        wb = build_lender_package_workbook(
            meta, tb_rows, fs_lines,
            validation_items=validation_items or None,
            issues=issues or None,
        )

    else:
        # Fallback: empty TB workbook
        wb = build_trial_balance_workbook(meta, [])

    return workbook_to_bytes(wb, generation_time=meta.generation_time)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_report_run_or_raise(db: Session, run_id: int) -> ReportRun:
    run = db.get(ReportRun, run_id)
    if run is None:
        raise ReportRunNotFoundError(f"ReportRun id={run_id} not found")
    return run


def list_report_runs(
    db: Session,
    organization_id: int,
    report_type: str | None = None,
    status: str | None = None,
    entity_id: int | None = None,
) -> list[ReportRun]:
    q = db.query(ReportRun).filter(ReportRun.organization_id == organization_id)
    if report_type:
        q = q.filter(ReportRun.report_type == report_type)
    if status:
        q = q.filter(ReportRun.status == status)
    if entity_id:
        q = q.filter(ReportRun.entity_id == entity_id)
    return q.order_by(ReportRun.created_at.desc()).all()


def create_report_run(
    db: Session,
    organization_id: int,
    report_type: str,
    output_format: str = "xlsx",
    entity_id: int | None = None,
    accounting_period_id: int | None = None,
    scenario_ids: list[int] | None = None,
    parameters: dict | None = None,
    acting_user: User | None = None,
) -> ReportRun:
    if report_type not in REPORT_TYPES:
        raise ReportValidationError(
            f"Unknown report_type '{report_type}'. "
            f"Valid: {sorted(REPORT_TYPES)}"
        )
    if output_format not in OUTPUT_FORMATS:
        raise ReportValidationError(
            f"Unknown output_format '{output_format}'. Valid: {sorted(OUTPUT_FORMATS)}"
        )

    run = ReportRun(
        organization_id=organization_id,
        created_by_user_id=acting_user.id if acting_user else None,
        report_type=report_type,
        output_format=output_format,
        status="pending",
        entity_id=entity_id,
        accounting_period_id=accounting_period_id,
        scenario_ids_json=json.dumps(scenario_ids) if scenario_ids else None,
        parameters_json=json.dumps(parameters) if parameters else None,
    )
    db.add(run)
    db.flush()
    return run


def execute_report_run(
    db: Session,
    run_id: int,
    storage: StorageBackend,
    org_slug: str,
    acting_user: User | None = None,
) -> ReportRun:
    run = get_report_run_or_raise(db, run_id)

    if run.status in ("running", "completed"):
        raise ReportRunStateError(
            f"ReportRun id={run_id} is already {run.status}. Use rerun to generate again."
        )

    run.status = "running"
    db.flush()

    try:
        wf_summary = _collect_workflow_summary(db, run)
        run.workflow_summary_json = json.dumps(wf_summary)
        db.flush()

        file_bytes = _dispatch_report(db, run)

        ext = ".xlsx" if run.output_format == "xlsx" else f".{run.output_format}"
        file_name = f"{run.report_type}_{uuid.uuid4().hex}{ext}"
        storage_path = f"{org_slug}/reports/{file_name}"
        storage.save(storage_path, file_bytes)

        from app.models.document import Document
        from app.services.storage_service import compute_checksum

        checksum = compute_checksum(file_bytes)
        doc_type = REPORT_TYPE_DOC_TYPE.get(run.report_type, "other")
        doc = Document(
            organization_id=run.organization_id,
            uploaded_by_user_id=run.created_by_user_id,
            file_name=file_name,
            original_file_name=file_name,
            file_extension=ext,
            mime_type=(
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                if run.output_format == "xlsx"
                else "text/plain"
            ),
            file_size_bytes=len(file_bytes),
            storage_path=storage_path,
            document_type=doc_type,
            checksum_sha256=checksum,
        )
        db.add(doc)
        db.flush()

        run.generated_document_id = doc.id
        run.storage_path = storage_path
        run.status = "completed"
        run.completed_at = datetime.datetime.now(datetime.UTC)
        db.flush()

    except Exception:
        run.status = "failed"
        db.flush()
        raise

    return run


def rerun_report(
    db: Session,
    run_id: int,
    storage: StorageBackend,
    org_slug: str,
    acting_user: User | None = None,
) -> ReportRun:
    """Create a new ReportRun from the same parameters and execute it."""
    original = get_report_run_or_raise(db, run_id)

    new_run = create_report_run(
        db,
        organization_id=original.organization_id,
        report_type=original.report_type,
        output_format=original.output_format,
        entity_id=original.entity_id,
        accounting_period_id=original.accounting_period_id,
        scenario_ids=_get_scenario_ids(original) or None,
        parameters=json.loads(original.parameters_json) if original.parameters_json else None,
        acting_user=acting_user,
    )

    return execute_report_run(db, new_run.id, storage, org_slug, acting_user=acting_user)
